@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title "Digital Wallet Full Cycle"
Person("client", "Client", "Digital Wallet User")
System("Wallet", "Digital Wallet System", "FC Digital Wallet")

@enduml